# This file is part of the `youdirk_numeric_io` Minecraft mod
# Copyright (C) 2019  Dirk "YouDirk" Lehmann
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

title: YouDirk Numeric I/O
description: A Minecraft Forge mod for decimal I/O support

# Variables from theme
theme: jekyll-theme-architect
show_downloads: true
google_analytics:

github:
  zip_url: https://github.com/YouDirk/youdirk_numeric_io/raw/master/docs/maven/net/dj_l/youdirk_numeric_io/1.13-0.0.0.1-dummy/youdirk_numeric_io-1.13-0.0.0.1-dummy.jar
  tar_url: https://github.com/YouDirk/youdirk_numeric_io/raw/master/docs/maven/net/minecraftforge/forge/1.13.2-25.0.214/forge-1.13.2-25.0.214-installer.jar
numeric_io:
  version_stable: 1.13.2-0.0.0.2-dummy
  github_url: https://github.com/YouDirk/youdirk_numeric_io
  website_url: https://youdirk.github.io/youdirk_numeric_io
  downloads_rel_url: downloads
  wiki_rel_url: wiki
  issues_rel_url: issues
  contribdoc_rel_url: blob/master/CONTRIBUTING.md
  github_maven_url: https://github.com/YouDirk/youdirk_numeric_io/raw/master/docs/maven

# Some advantages ...

# Generating a sitemap.xml for Google Search Console
plugins:
  - jekyll-sitemap

sass:
  style: compressed

exclude:
- maven/net/dj_l/youdirk_numeric_io/pom.templ.xml
- _config.templ.yml
- _data/builds.templ.json
- _data/forge_builds.templ.json
